trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
- name: buildConfiguration
  value: 'release'
- name: buildPlatform
  value: 'any cpu'  
- name: GitVersion.AssemblySemFileVer
  value: ''

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.26
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks
