trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

workspace:
  clean: all

variables:
- group: 'Prod Management Resources'
- name: buildConfiguration
  value: 'release'
- name: buildPlatform
  value: 'any cpu'  
- name: GitVersion.AssemblySemFileVer
  value: ''

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml