parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
    workspace:
      clean: all
  variables:
  - group: BUILD Management Resources
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      ContinueOnVulnerablePackageScanError: true

  - task: DotNetCoreCLI@2
    displayName: Publish - dotnet publish ${{ parameters.SolutionBaseName }}.Api
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/${{ parameters.SolutionBaseName }}.Api/${{ parameters.SolutionBaseName }}.Api.csproj
      arguments: -o $(build.artifactstagingdirectory)/publish -c ${{ parameters.BuildConfiguration }} --no-build
      modifyOutputPath: true
      zipAfterPublish: true

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish

  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifact
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: ${{ parameters.SolutionBaseName }}
      
- job: NET_Core_CodeBuild
  pool:
    name: DAS - Continuous Integration Agents
  variables:
  - group: BUILD Management Resources
  workspace:
    clean: all
  steps:
  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      TargetProjects: 'src/EmployerProfiles/**/*.csproj'
      UnitTestProjects: 'src/EmployerProfiles/**/*UnitTests.csproj'
      ContinueOnVulnerablePackageScanError: true      

  - task: DotNetCoreCLI@2
    displayName: Publish Employer Profiles API
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/EmployerProfiles/SFA.DAS.EmployerProfiles.Api/SFA.DAS.EmployerProfiles.Api.csproj
      arguments: -o $(build.artifactstagingdirectory)/publish -c ${{ parameters.buildConfiguration }} --no-build
      modifyOutputPath: true
      zipAfterPublish: true

  - task: CopyFiles@2
    displayName: 'Copy azure Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      contents: |
        azure/**
      targetFolder: '$(Build.ArtifactStagingDirectory)/publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Publish'
    inputs:
      ArtifactName: Publish
      pathtoPublish: '$(build.artifactstagingdirectory)/publish'
